export default[
    { "_id": "Q101", "title": "Q1-HTML", "course": "RS101", "availableUntil": "2024-04-28",  "due": "2024-04-22", "points": "20", "length": "4",
      "type": "Graded Quiz",
      "group": "QUIZZES",
      "shuffle": "No",
      "time": "20 minutes",
      "attempt": "No",
      "show": "No",
      "access": "123",
      "one": "Yes",
      "webcam": "No",
      "lock": "No",
      "available": "2024-01-01",
  },
    { "_id": "Q102", "title": "Q2-CSS", "course": "RS101", "availableUntil": "2024-04-28",  "due": "2024-04-22", "points": "30", "length": "6",
    "type": "Graded Quiz",
    "group": "QUIZZES",
    "shuffle": "No",
    "time": "20 minutes",
    "attempt": "No",
    "show": "No",
    "access": "123",
    "one": "Yes",
    "webcam": "No",
    "lock": "No",
    "available": "2024-01-01", },
    { "_id": "Q103", "title": "Q3-REACT", "course": "RS101", "availableUntil": "2024-04-28",  "due": "2024-04-22", "points": "20", "length": "4",
    "type": "Graded Quiz",
    "group": "QUIZZES",
    "shuffle": "No",
    "time": "20 minutes",
    "attempt": "No",
    "show": "No",
    "access": "123",
    "one": "Yes",
    "webcam": "No",
    "lock": "No",
    "available": "2024-01-01", },
    { "_id": "Q201", "title": "Q1-Aerodynamics Quiz", "course": "RS102", "availableUntil": "2024-04-28",  "due": "2024-04-22", "points": "20", "length": "4",
    "type": "Graded Quiz",
    "group": "QUIZZES",
    "shuffle": "No",
    "time": "20 minutes",
    "attempt": "No",
    "show": "No",
    "access": "123",
    "one": "Yes",
    "webcam": "No",
    "lock": "No",
    "available": "2024-01-01", },
    { "_id": "Q202", "title": "Q2-Flow Analysis", "course": "RS102", "availableUntil": "2024-04-28",  "due": "2024-04-22", "points": "20", "length": "4",
    "type": "Graded Quiz",
    "group": "QUIZZES",
    "shuffle": "No",
    "time": "20 minutes",
    "attempt": "No",
    "show": "No",
    "access": "123",
    "one": "Yes",
    "webcam": "No",
    "lock": "No",
    "available": "2024-01-01", },
    { "_id": "Q203", "title": "Q3-Heating Analysis", "course": "RS102", "availableUntil": "2024-04-28",  "due": "2024-04-22", "points": "20", "length": "4",
    "type": "Graded Quiz",
    "group": "QUIZZES",
    "shuffle": "No",
    "time": "20 minutes",
    "attempt": "No",
    "show": "No",
    "access": "123",
    "one": "Yes",
    "webcam": "No",
    "lock": "No",
    "available": "2024-01-01", },
    { "_id": "Q301", "title": "Q1-Design Task", "course": "RS103", "availableUntil": "2024-04-28",  "due": "2024-04-22", "points": "20", "length": "4",
    "type": "Graded Quiz",
    "group": "QUIZZES",
    "shuffle": "No",
    "time": "20 minutes",
    "attempt": "No",
    "show": "No",
    "access": "123",
    "one": "Yes",
    "webcam": "No",
    "lock": "No",
    "available": "2024-01-01", },
    { "_id": "Q302", "title": "Q2-Orbital Calculations", "course": "RS103", "availableUntil": "2024-04-28",  "due": "2024-04-22", "points": "20", "length": "4",
    "type": "Graded Quiz",
    "group": "QUIZZES",
    "shuffle": "No",
    "time": "20 minutes",
    "attempt": "No",
    "show": "No",
    "access": "123",
    "one": "Yes",
    "webcam": "No",
    "lock": "No",
    "available": "2024-01-01", },
    { "_id": "Q303", "title": "Q3-Spacecraft Design Exam", "course": "RS103", "availableUntil": "2024-04-28",  "due": "2024-04-22", "points": "20", "length": "4",
    "type": "Graded Quiz",
    "group": "QUIZZES",
    "shuffle": "No",
    "time": "20 minutes",
    "attempt": "No",
    "show": "No",
    "access": "123",
    "one": "Yes",
    "webcam": "No",
    "lock": "No",
    "available": "2024-01-01", }
    
  ]